#!/bin/sh
# fluxbox startup-script:
# Lines starting with a '#' are ignored.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.


#~ sleep 1 && unclutter -root & - MOVED TO /etc/default/unclutter
#~ xxkb&                        - MOVED TO ~/.xsession
#~ conky&                       - MOVED TO ~/.xsession
#~ conky -c ~/.conkyrc-diclock& - MOVED TO ~/.xsession
~/bin/userapps.d.sh&

#(sleep 3; gmpc&)&
(sleep 3; exec ~/misc/src/sonata/sonata.py&)&
~/misc/src/gajim/launch.sh&
urxvt -name Terminal&


# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.
#xcompmgr -n&
exec fluxbox
# or if you want to keep a log:
#~exec fluxbox -log "/home/sio/.fluxbox/log"
