#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
#xmodmap "/home/sio/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
sleep 1 && unclutter -root &
sleep 2 && xxkb&
sleep 1 && conky&
sleep 1 && conky -c ~/.conkyrc-diclock&
sleep 5 && gmpc&
#gajim&
~/src/gajim/launch.sh&
urxvt -name Terminal&
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/sio/.fluxbox/log"
